### ISSUE TITLE
Can't launch steam or GOG galaxy

### ISSUE THREAD

**Issue by akenbake** [lyckantropen/moonlight_hdr_launcher#2]
I'm using moonlight and trying to launch Steam in big picture mode.

moonlight_hdr_launcher.ini:
```
[options]
launcher_exe=gamestream_launchpad.exe 3840 2160 gamestream_steam_bp.ini
wait_on_process=1
toggle_hdr = 1
```

gamestream_steam_bp.ini:
```
[LAUNCHER]
launcher_path = C:\Program Files (x86)\Steam\steam.exe steam://open/bigpicture Fullscreen
# set it to something other than Steam because gamestream_launchpad can detect multiple windows and will close prematurely
launcher_window_name = NotSteam

[BACKGROUND]
# List as many exe's or bat's as you want here. They will run at the start of the GameStream session and be killed at the end.
# background_exe_1 = C:\Program Files (x86)\JoyToKey\JoyToKey.exe
# background_exe_2 = C:\WINDOWS\system32\mspaint.exe
# background_exe_1 = C:\Program Files\moonlight_hdr_launcher\hdr_toggle.exe

[SETTINGS]
debug = 0
sleep_on_exit = 0
close_watch_method = window
```

In moonlight, I start the session by clicking the "Steam OS" icon. This successfully starts streaming my desktop in the correct 4k resolution. However, steam is not opening at all. I also tried using gamestream_gog_galaxy.ini and that did not open GOG Galaxy either.

Here is the output from moonlight_hdr_launcher_log.txt:
```
2020-12-25 23:39:17: argv[0]: MassEffectAndromeda.exe
2020-12-25 23:39:17: Found config file: moonlight_hdr_launcher.ini
```

**Comment by lyckantropen** [comment]
Hi, can you see what happens if you run Mass effect andromeda.exe directly?

**Comment by akenbake** [comment]
Nothing happens when I run MassEffectAndromeda.exe directly on my PC - neither GOG or Steam will open. I do see a new moonlight_hdr_launcher_log.txt generated each time that I run it, but it always contains the same information:

```
2020-12-27 12:37:50: argv[0]: C:\Program Files\moonlight_hdr_launcher\MassEffectAndromeda.exe
2020-12-27 12:37:50: Found config file: C:\Program Files\moonlight_hdr_launcher\moonlight_hdr_launcher.ini
```

If I open a CMD prompt, I can get GOG Galaxy and Steam to open by:

```
gamestream_launchpad.exe 3840 2160 gamestream_steam_bp.ini
gamestream_launchpad.exe 3840 2160 gamestream_gog_galaxy.ini
```

So there appears to be something wrong with the moonlight_hdr_launcher.ini file. I tried "Taking Ownership" of the moonlight_hdr_launcher folder and files, as well as running exe files as Administrator, but the result is the same

**Comment by akenbake** [comment]
Ok, I got farther. Apparently lower-case does NOT work for [options] in moonlight_hdr_launcher.ini:

```
[options]
launcher_exe=gamestream_launchpad.exe 3840 2160 gamestream_steam_bp.ini
wait_on_process=1
toggle_hdr = 1
```

I must use upper-case for it to work:
```
[OPTIONS]
launcher_exe=gamestream_launchpad.exe 3840 2160 gamestream_steam_bp.ini
wait_on_process=1
toggle_hdr = 1
```


Now, the weird thing is that GOG Galaxy is opening when I'm trying to open Steam as seen above. Is there anything hardcoded to look for GOG Galaxy 2.0? I don't understand how GOG Galaxy could be opening with the above moonlight_hdr_launcher.ini file pointing to gamestream_steam_bp.ini

Here is my gamestream_steam_bp.ini file for reference:

```
[LAUNCHER]
launcher_path = C:\Program Files (x86)\Steam\steam.exe steam://open/bigpicture Fullscreen
# set it to something other than Steam because gamestream_launchpad can detect multiple windows and will close prematurely
launcher_window_name = NotSteam

[BACKGROUND]
# List as many exe's or bat's as you want here. They will run at the start of the GameStream session and be killed at the end.
# background_exe_1 = C:\Program Files (x86)\JoyToKey\JoyToKey.exe
# background_exe_2 = C:\WINDOWS\system32\mspaint.exe
# background_exe_1 = C:\Program Files\moonlight_hdr_launcher\hdr_toggle.exe

[SETTINGS]
debug = 0
sleep_on_exit = 0
close_watch_method = window
```

Here is my moonlight_hdr_launcher_log.txt
```
2020-12-27 12:57:12: argv[0]: C:\Program Files\moonlight_hdr_launcher\MassEffectAndromeda.exe
2020-12-27 12:57:12: Found config file: C:\Program Files\moonlight_hdr_launcher\moonlight_hdr_launcher.ini
2020-12-27 12:57:12: Launching 'C:/Program Files (x86)/GOG Galaxy/GalaxyClient.exe' and waiting for it to complete.
```

**Comment by akenbake** [comment]
There is something hardcoded to open GOG Galaxy. I modified moonlight_hdr_launcher.ini to point to a non-existent exe and it still results in GOG Galaxy being opened:

```
[OPTIONS]
launcher_exe = randomgarbage.exe
wait_on_process = 1
toggle_hdr = 1
```

Not sure how to figure this one out, so I'll wait for your support. Thanks!

**Comment by akenbake** [comment]
The reason why upper-case OPTIONS worked, is it because it defaulted to working values in main.cpp:

```
const static std::string default_launcher = "C:/Program Files (x86)/GOG Galaxy/GalaxyClient.exe";
...
std::string launcher_exe = default_launcher;
bool wait_on_process = true;
bool toggle_hdr = false;
```

The real issue that I don't have an HDR capable monitor, so something was getting hung up when trying to toggle HDR. I now have it working with Steam big picture mode using:

```
[options]
launcher_exe = gamestream_launchpad.exe 3840 2160 gamestream_steam_bp.ini
wait_on_process = 1
toggle_hdr = 0
```

However, I am not getting HDR in any games launched from Steam big picture mode. Do you know what tmac666 is doing under the hood to get it working? Admittedly, I haven't tried tmac666's fix because the source code isn't open and he seems to ignore everyones request to see it - seems very shady.

I may end up ordering one of those HDMI HDR dummy plugs so that I can take full advantage of your implementation. Thanks!

**Comment by lyckantropen** [comment]
Thanks for investigating, I'll look more closely today evening when I come
back from Christmas.

niedz., 27 gru 2020, 23:46 użytkownik akenbake <notifications@github.com>
napisał:

**Comment by Rabusek** [comment]
> However, I am not getting HDR in any games launched from Steam big picture mode. Do you know what tmac666 is doing under the hood to get it working? Admittedly, I haven't tried tmac666's fix because the source code isn't open and he seems to ignore everyones request to see it - seems very shady.

Bear in mind this will only work for games that do not have os-level HDR - so ie. CP2077, FFXV will **not** work.

If you decide to get the dongle, make sure you get one that supports your input (ie. if you plan to play 4k hdr, get one that supports it) - i almost got a 10$ one that did not support my input. I heard LINDY 32115 is pretty good and got that one - will test on Wednesday and can tell you if i got it working on 4k hdr by then.

**Comment by lyckantropen** [comment]
Hi, please install the latest release (1.0.3) and if problems persist, attach the `moonlight_hdr_launcher_install.log` file that will be created alongside `install.exe` as well as `moonlight_hdr_launcher_log.txt` from `C:\Program Files\moonlight_hdr_launcher\`.

Bear in mind that installation will overwrite your `moonlight_hdr_launcher.ini` file, so make a backup.

**Comment by j9ac9k** [comment]
I believe I'm having the same issue (currently running 1.0.3).

A little information; host has a dummy display port dongle emulating a non-HDR display being attached.  Client has an ultra-wide HDR capable monitor

`moonlight_hdr_launcher_log.txt`

```
2020-12-28 21:10:20: Working folder read from registry: C:\Program Files\moonlight_hdr_launcher
2020-12-28 21:10:20: argv[0]: MassEffectAndromeda.exe
2020-12-28 21:10:20: Found config file: C:\Program Files\moonlight_hdr_launcher\moonlight_hdr_launcher.ini
2020-12-28 21:10:20: options.launcher_exe=gamestream_launchpad.exe 3840 1600 gamestream_steam_bp.ini
2020-12-28 21:10:20: options.wait_on_process=1
2020-12-28 21:10:20: options.toggle_hdr=1
2020-12-28 21:10:20: Attempting to set HDR mode
```

`moonlight_hdr_launcher.ini`

```
[options]
# command to launch when the launcher is executed  
; launcher_exe = C:\Program Files (x86)\Steam\steam.exe steam://open/bigpicture

# wait for the launcher process to exit or detach immediately
# useful with gamestream_launchpad to close the connection
# and with toggle_hdr=1
; wait_on_process = 0

# enable HDR on all supported monitors for the duration of the launcher
# only works with wait_on_process=1
; toggle_hdr = 0

## Examples
# launch Steam in Big Picture mode
; launcher_exe = C:\Program Files (x86)\Steam\steam.exe steam://open/bigpicture
; wait_on_process = 0

# launch GOG Galaxy using gamestream_launchpad
launcher_exe=gamestream_launchpad.exe 3840 1600 gamestream_steam_bp.ini
wait_on_process=1
toggle_hdr = 1
```

`gamestream_steam_bp.ini`

```
[LAUNCHER]
launcher_path = C:\Games\Steam\steam.exe steam://open/bigpicture Fullscreen
# set it to something other than Steam because gamestream_launchpad can detect multiple windows and will close prematurely
launcher_window_name = NotSteam

[BACKGROUND]
# List as many exe's or bat's as you want here. They will run at the start of the GameStream session and be killed at the end.
# background_exe_1 = C:\Program Files (x86)\JoyToKey\JoyToKey.exe
# background_exe_2 = C:\WINDOWS\system32\mspaint.exe
# background_exe_1 = C:\Program Files\moonlight_hdr_launcher\hdr_toggle.exe

[SETTINGS]
debug = 0
sleep_on_exit = 0
close_watch_method = window
```

(the non-default location of steam is intentional, that is where the executable is loaded).

First thing to point out is that the resolution is definitely not 3840 x 1600, but something far lower (maybe 1920 x 1080?).  Also steam does not launch (just hangs there on the desktop).

I was running the Mass Effect Andromeda "game" from moonlight on the client.

**Comment by j9ac9k** [comment]
lastly, I too was able to run `gamestream.txt 3840 1600 gamestream_steam_bp.ini` from the command prompt (when logged in via parsec) and steam launched successfully

**Comment by lyckantropen** [comment]
It seems to be crashing when trying to set the HDR mode. What is your card,
do you have the latest GameReady driver and latest GeForce Experience?

wt., 29 gru 2020, 06:39 użytkownik Ogi Moore <notifications@github.com>
napisał:

**Comment by lyckantropen** [comment]
Does it work in non-HDR mode when toggle_hdr is set to 0?

wt., 29 gru 2020, 06:42 użytkownik Karol Trojanowski <
trojanowski.ifuj@gmail.com> napisał:

**Comment by j9ac9k** [comment]
Hi @lyckantropen thanks for the follow up.

I have a Quadro RTX 4000 

I believe I have the current Geforce Driver

![image](https://user-images.githubusercontent.com/646398/103261698-485d7980-4957-11eb-9f19-942c8d8ff1d8.png)

I'm running GeForce Experience 3.20.5.70

![image](https://user-images.githubusercontent.com/646398/103261731-61662a80-4957-11eb-83b1-cca1e25aeedd.png)

Setting `toggle_hdr` to 0 also just takes me to the desktop with the 1280x720 resolution, but the log has a different error


```
2020-12-28 22:00:14: Working folder read from registry: C:\Program Files\moonlight_hdr_launcher
2020-12-28 22:00:14: argv[0]: MassEffectAndromeda.exe
2020-12-28 22:00:14: Found config file: C:\Program Files\moonlight_hdr_launcher\moonlight_hdr_launcher.ini
2020-12-28 22:00:14: options.launcher_exe=gamestream_launchpad.exe 3840 1600 gamestream_steam_bp.ini
2020-12-28 22:00:14: options.wait_on_process=1
2020-12-28 22:00:14: options.toggle_hdr=0
2020-12-28 22:00:14: Launching 'gamestream_launchpad.exe 3840 1600 gamestream_steam_bp.ini' and waiting for it to complete.
2020-12-28 22:00:14: Error:  CreateProcess failed: The system cannot find the file specified.
```

Contents of my directory:

![image](https://user-images.githubusercontent.com/646398/103261984-6081c880-4958-11eb-991b-8468057b2f15.png)

**Comment by j9ac9k** [comment]
Seeing that error, I thought I should put the full path to the `gamestream_launchpad.exe` executable, did that, got a different error in the log:

```
2020-12-28 22:15:29: Working folder read from registry: C:\Program Files\moonlight_hdr_launcher
2020-12-28 22:15:29: argv[0]: MassEffectAndromeda.exe
2020-12-28 22:15:29: Found config file: C:\Program Files\moonlight_hdr_launcher\moonlight_hdr_launcher.ini
2020-12-28 22:15:29: options.launcher_exe=C:\Program Files\moonlight_hdr_launcher\gamestream_launchpad.exe 3840 1600 gamestream_steam_bp.ini
2020-12-28 22:15:29: options.wait_on_process=1
2020-12-28 22:15:29: options.toggle_hdr=0
2020-12-28 22:15:29: Launching 'C:\Program Files\moonlight_hdr_launcher\gamestream_launchpad.exe 3840 1600 gamestream_steam_bp.ini' and waiting for it to complete.
2020-12-28 22:15:36: The command "C:\Program Files\moonlight_hdr_launcher\gamestream_launchpad.exe 3840 1600 gamestream_steam_bp.ini" has terminated with exit code -1
```

**Comment by lyckantropen** [comment]
You could try setting the path to the ini file absolute as well. I'm seeing
the problem though: the current folder should be set but it's not. I'll
look into it soon.

wt., 29 gru 2020, 07:18 użytkownik Ogi Moore <notifications@github.com>
napisał:

**Comment by j9ac9k** [comment]
putting the full path to the .ini looks like it did the trick ...the resolution matches up; ...got some other weird behavior but I think that it's my fault...I'll investigate more.

**Comment by j9ac9k** [comment]
ok, ... so setting `toggle_hdr = 1` results in the same behavior as before.

with `toggle_hdr = 0` it's not actually loading steam, but playnite, which I was experimenting with earlier using gamestream launchpad, but the contents of the ini file I'm passing in my config makes no reference to playnite.

log:

```
2020-12-28 22:26:01: Working folder read from registry: C:\Program Files\moonlight_hdr_launcher
2020-12-28 22:26:01: argv[0]: MassEffectAndromeda.exe
2020-12-28 22:26:01: Found config file: C:\Program Files\moonlight_hdr_launcher\moonlight_hdr_launcher.ini
2020-12-28 22:26:01: options.launcher_exe=C:\Program Files\moonlight_hdr_launcher\gamestream_launchpad.exe 3840 1600 C:\Program Files\moonlight_hdr_launcher\gamestream_steam_bp.ini
2020-12-28 22:26:01: options.wait_on_process=1
2020-12-28 22:26:01: options.toggle_hdr=0
2020-12-28 22:26:01: Launching 'C:\Program Files\moonlight_hdr_launcher\gamestream_launchpad.exe 3840 1600 C:\Program Files\moonlight_hdr_launcher\gamestream_steam_bp.ini' and waiting for it to complete.
2020-12-28 22:26:24: SUBPROCESS: SUCCESS: The process "nvstreamer.exe" with PID 8744 has been terminated.

2020-12-28 22:26:25: SUBPROCESS: Switching resolution to 3840x1600

2020-12-28 22:26:25: SUBPROCESS: Minimizing windows

2020-12-28 22:26:25: SUBPROCESS: Starting game launcher

2020-12-28 22:26:25: SUBPROCESS: Focusing Playnite

2020-12-28 22:26:25: SUBPROCESS: Watching for launcher window to close

2020-12-28 22:26:25: SUBPROCESS: Terminating GameStream session.

2020-12-28 22:26:25: SUBPROCESS: Restoring original resolution.

2020-12-28 22:26:25: The command "C:\Program Files\moonlight_hdr_launcher\gamestream_launchpad.exe 3840 1600 C:\Program Files\moonlight_hdr_launcher\gamestream_steam_bp.ini" has terminated with exit code -1073741510
```

and for double-quadruple checking my `gamestream_steam_bp.ini` file contains:

```
[LAUNCHER]
launcher_path = C:\Games\Steam\steam.exe steam://open/bigpicture Fullscreen
# set it to something other than Steam because gamestream_launchpad can detect multiple windows and will close prematurely
launcher_window_name = NotSteam

[BACKGROUND]
# List as many exe's or bat's as you want here. They will run at the start of the GameStream session and be killed at the end.
# background_exe_1 = C:\Program Files (x86)\JoyToKey\JoyToKey.exe
# background_exe_2 = C:\WINDOWS\system32\mspaint.exe
# background_exe_1 = C:\Program Files\moonlight_hdr_launcher\hdr_toggle.exe

[SETTINGS]
debug = 0
sleep_on_exit = 0
close_watch_method = window
```

**Comment by lyckantropen** [comment]
I'll improve the error handling of NVAPI functions so we get more
information as to why it can't enable HDR. Don't hold your breath though,
it's early morning where I am :)

wt., 29 gru 2020, 07:30 użytkownik Ogi Moore <notifications@github.com>
napisał:

**Comment by j9ac9k** [comment]
It's getting late where I am, so don't rush on my account.  Thanks for looking into it, let me know if there is any other configuration/testing I can do to help out.

**Comment by lyckantropen** [comment]
With release 1.0.5 the issue with relative paths to `C:\Program Files\moonlight_hdr_launcher` in `launcher_exe` is now fixed. I have added better exception handling in NVAPI calls so now NVAPI errors should be logged with meaningful messages.

**Comment by j9ac9k** [comment]
For sanity sake, I tried this twice; but 1.0.5 behavior is identical to that of 1.0.3

First, the `moonlight_hdr_launcher.ini` does not appear to be read/used at all due to incorrect permissions.  Adding myself as the principal for the file with full access was a required first step.

Then running with `toggle_hdr=1` I get the following log file

```
2020-12-29 09:01:30: Working folder read from registry: C:\Program Files\moonlight_hdr_launcher
2020-12-29 09:01:30: argv[0]: MassEffectAndromeda.exe
2020-12-29 09:01:30: Found config file: C:\Program Files\moonlight_hdr_launcher\moonlight_hdr_launcher.ini
2020-12-29 09:01:30: options.launcher_exe=gamestream_launchpad.exe 3840 1600 gamestream_steam_bp.ini
2020-12-29 09:01:30: options.wait_on_process=1
2020-12-29 09:01:30: options.toggle_hdr=1
2020-12-29 09:01:30: Attempting to set HDR mode
```

for `toggle_hdr = 0`; I still get the same application not found business...

Putting the full paths to the .ini and `gamestream_launcher` , it starts, but it does not launch steam, but launches playnite instead ...also the resolution that was set was incorrect (appears to be 2560 x 1600 not 3840 x 1600 (I periodically use 2560x1600 as that is the native display resolution for the built-in monitor of my laptop, but that is not what the config file I am using suggests to use)).

Here are the contents of the log file.

```
2020-12-29 09:06:14: Working folder read from registry: C:\Program Files\moonlight_hdr_launcher
2020-12-29 09:06:14: argv[0]: MassEffectAndromeda.exe
2020-12-29 09:06:14: Found config file: C:\Program Files\moonlight_hdr_launcher\moonlight_hdr_launcher.ini
2020-12-29 09:06:14: options.launcher_exe=C:\Program Files\moonlight_hdr_launcher\gamestream_launchpad.exe 3840 1600 C:\Program Files\moonlight_hdr_launcher\gamestream_steam_bp.ini
2020-12-29 09:06:14: options.wait_on_process=1
2020-12-29 09:06:14: options.toggle_hdr=0
2020-12-29 09:06:14: Launching 'C:\Program Files\moonlight_hdr_launcher\gamestream_launchpad.exe 3840 1600 C:\Program Files\moonlight_hdr_launcher\gamestream_steam_bp.ini' and waiting for it to complete.
2020-12-29 09:08:30: SUBPROCESS: SUCCESS: The process "nvstreamer.exe" with PID 13296 has been terminated.

2020-12-29 09:08:30: SUBPROCESS: Switching resolution to 3840x1600

2020-12-29 09:08:30: SUBPROCESS: Minimizing windows

2020-12-29 09:08:30: SUBPROCESS: Starting game launcher

2020-12-29 09:08:30: SUBPROCESS: Focusing Playnite

2020-12-29 09:08:30: SUBPROCESS: Watching for launcher window to close

2020-12-29 09:08:30: SUBPROCESS: Terminating GameStream session.

2020-12-29 09:08:30: SUBPROCESS: Restoring original resolution.

2020-12-29 09:08:30: The command "C:\Program Files\moonlight_hdr_launcher\gamestream_launchpad.exe 3840 1600 C:\Program Files\moonlight_hdr_launcher\gamestream_steam_bp.ini" has terminated with exit code -1073741510
```

Contents of my `moonlight_hdr_launcher` directory

![image](https://user-images.githubusercontent.com/646398/103301219-bcc70580-49b5-11eb-8de7-f7814c4dbb45.png)

Contents of `moonlight_hdr_launcher.ini`

```
[options]
# command to launch when the launcher is executed  
; launcher_exe = C:\Program Files (x86)\Steam\steam.exe steam://open/bigpicture

# wait for the launcher process to exit or detach immediately
# useful with gamestream_launchpad to close the connection
# and with toggle_hdr=1
; wait_on_process = 0

# enable HDR on all supported monitors for the duration of the launcher
# only works with wait_on_process=1
; toggle_hdr = 0

## Examples
# launch Steam in Big Picture mode
; launcher_exe = C:\Program Files (x86)\Steam\steam.exe steam://open/bigpicture
; wait_on_process = 0

# launch GOG Galaxy using gamestream_launchpad
; launcher_exe=gamestream_launchpad.exe 2560 1440 gamestream_gog_galaxy.ini
launcher_exe = C:\Program Files\moonlight_hdr_launcher\gamestream_launchpad.exe 3840 1600 C:\Program Files\moonlight_hdr_launcher\gamestream_steam_bp.ini
wait_on_process = 1
toggle_hdr = 0
```

Contents of `gamestream_steam_bp.ini`

```
[LAUNCHER]
launcher_path = C:\Games\Steam\steam.exe steam://open/bigpicture Fullscreen
# set it to something other than Steam because gamestream_launchpad can detect multiple windows and will close prematurely
launcher_window_name = NotSteam

[BACKGROUND]
# List as many exe's or bat's as you want here. They will run at the start of the GameStream session and be killed at the end.
# background_exe_1 = C:\Program Files (x86)\JoyToKey\JoyToKey.exe
# background_exe_2 = C:\WINDOWS\system32\mspaint.exe
# background_exe_1 = C:\Program Files\moonlight_hdr_launcher\hdr_toggle.exe

[SETTINGS]
debug = 0
sleep_on_exit = 0
close_watch_method = window
```

Let me know if there is any other information I can provide.

**Comment by lyckantropen** [comment]
Thanks @j9ac9k

Please do the following:
* Check the version of the `MassEffectAndromeda.exe` binary, by viewing the Details tab of the file's properties and verify that it is indeed 1.0.5.
* Attach the installer log (`moonlight_hdr_launcher_install.log`).
* Retry after removing the folder `C:\Program Files\moonlight_hdr_launcher` by hand and re-running the installer.
* Check if `<user folder>\AppData\Local\NVIDIA\NvBackend\StreamingAssetsData\mass_effect_andromeda\<number>\` exists and attach the contents of `StreamingSettings.json`.

The installer is setting the permissions to `C:\Program Files\moonlight_hdr_launcher` so it's writable by the user. There has to be something wrong if it's launching Playnite - perhaps some hardoded defaults in `gamestream_launcher`.

**Comment by j9ac9k** [comment]
> Thanks @j9ac9k
> 
> Please do the following:
> 
> * Check the version of the `MassEffectAndromeda.exe` binary, by viewing the Details tab of the file's properties and verify that it is indeed 1.0.5.

I get no version information on the details tab:

![image](https://user-images.githubusercontent.com/646398/103302831-6b207a00-49b9-11eb-9bb7-6f98ec3da484.png)

> * Attach the installer log (`moonlight_hdr_launcher_install.log`).

[moonlight_hdr_launcher_log.txt](https://github.com/lyckantropen/moonlight_hdr_launcher/files/5751604/moonlight_hdr_launcher_log.txt)

> * Retry after removing the folder `C:\Program Files\moonlight_hdr_launcher` by hand and re-running the installer.

I can do this again if you'd like, but this was the step I did when I re-ran the second time above.

> * Check if `<user folder>\AppData\Local\NVIDIA\NvBackend\StreamingAssetsData\mass_effect_andromeda\<number>\` exists and attach the contents of `StreamingSettings.json`.

[StreamingSettings.json.txt](https://github.com/lyckantropen/moonlight_hdr_launcher/files/5751615/StreamingSettings.json.txt)

(remove the `.txt` at the end).

> The installer is setting the permissions to `C:\Program Files\moonlight_hdr_launcher` so it's writable by the user. There has to be something wrong if it's launching Playnite - perhaps some hardoded defaults in `gamestream_launcher`.


Dumb question perhaps, but what "game" should I be launching from the moonlight client?

![image](https://user-images.githubusercontent.com/646398/103303195-395be300-49ba-11eb-9baa-11cf5411f84e.png)

I've been launching the "Mass Effect Andromeda" icon, should I be launching the "StreamOS" icon?

**Comment by lyckantropen** [comment]
It does seem like you're doing what you should be doing. I will double-check the release file because the executable should have version information.

There's only a couple reasons I can think of why you'd have separate entries for "Mass Effect Andromeda" and the "Steam OS" one:
* You actually have Mass Effect Andromeda installed.
* You've also been using tmac666's solution from the NVIDIA forums, I have no idea how that would work out, I haven't tested such a setup.
* GeForce Experience has cached both entries for some reason.

**Comment by j9ac9k** [comment]
> It does seem like you're doing what you should be doing. I will double-check the release file because the executable should have version information.
> 
> There's only a couple reasons I can think of why you'd have separate entries for "Mass Effect Andromeda" and the "Steam OS" one:
> 
> * You actually have Mass Effect Andromeda installed.

I do not have Mass Effect Andromeda installed

> * You've also been using tmac666's solution from the NVIDIA forums, I have no idea how that would work out, I haven't tested such a setup.

A few days ago, I attempted to the `mstsc.exe` rename trick per suggestion on the moonlight discord channel, but I had long since removed those entries from the geforce experience; but there could certainly be a cache laying around somewhere.

> * GeForce Experience has cached both entries for some reason.

Do you happen to know of a way I can nuke some of the caching here?

**Comment by lyckantropen** [comment]
> Do you happen to know of a way I can nuke some of the caching here?

You could try this:
* delete `<user folder>\AppData\Local\NVIDIA\NvBackend\StreamingAssetsData\`
* force-quit GeForce Experience or restart your PC
* re-scan for games in GeForce Experience

**Comment by j9ac9k** [comment]
> > Do you happen to know of a way I can nuke some of the caching here?
> 
> You could try this:
> 
> * delete `<user folder>\AppData\Local\NVIDIA\NvBackend\StreamingAssetsData\`
> * force-quit GeForce Experience or restart your PC
> * re-scan for games in GeForce Experience

I'll give this a go and retry... also FYI I ran a sha256 hash check on the MassEffectAndromeda.exe file:

![image](https://user-images.githubusercontent.com/646398/103304780-5abece00-49be-11eb-91be-dcc841c8bdf9.png)

(sorry copying text in/out of the host system here is a bit tricky)

**Comment by lyckantropen** [comment]
I have issued release 1.0.6 that will print version information in both the installer log and the launcher log. That way we know for sure.

Please retry using this version and attach both logs. Do a full wipe of `C:\Program Files\moonlight_hdr_launcher` beforehand.

BTW the reason `gamestream_launchpad.exe` might be launching Playnite is because the path to the `ini` has spaces and it is treating it as two arguments. You could try putting the path to the `ini` file in double quotes, just so it is just a single argument, or escaping the space with a `\` after `C:\Program`.

**Comment by j9ac9k** [comment]
This is interesting and potentially relevant, I'm having a hard time deleting the files inside the the `StreamingAssetsData" siting permission denied

![image](https://user-images.githubusercontent.com/646398/103305386-d9683b00-49bf-11eb-87c9-0405d1889234.png)

Checking security of those files, sure enough I do not have permissions directly (but as I'm an administrator, I can add myself)

**Comment by lyckantropen** [comment]
Oh, sorry. This is intentional, GeForce Experience will delete the entry otherwise because of reasons unbeknownst to me, but I suppose it can tell it's not real. You can change the permissions yourself.

**Comment by j9ac9k** [comment]
After nuking that directory; restarting, I am now unable to install 1.0.6 without error saying that geforce now can't find mass effect andromeda.  I have attached the logfile here, should I attempt to modify the 

[moonlight_hdr_launcher_install.log](https://github.com/lyckantropen/moonlight_hdr_launcher/files/5751791/moonlight_hdr_launcher_install.log)

On the plus side, in the executable properties, I can verify I have version 1.0.6

![image](https://user-images.githubusercontent.com/646398/103306895-8c866380-49c3-11eb-9f26-55828a8e3343.png)

**Comment by lyckantropen** [comment]
When I had this error I had to force quit Experience (kill anything
NVIDIA-related in task manager), temporarily rename
MassEffectAndromeda.exe, restart Experience, scan for games, rename
MassEffectAndromeda.exe
back to what it should be, scan for games and run the installer again.

Only this ensures that the cache for MEA is getting created so it can be
patched by the installer.

Perhaps restarting Experience is a necessary step that should be part of
the installation, but I haven't been able to make it consistent. Sometimes
it works, sometimes it doesn't.

wt., 29 gru 2020, 19:49 użytkownik Ogi Moore <notifications@github.com>
napisał:

**Comment by j9ac9k** [comment]
I'm still un-able to regenerate the MassEffectAndromeda directory in the `StreamingAssetsData` directory, and thus the installer is complaining about it not being found; I'll keep tinkering with this

**Comment by j9ac9k** [comment]
More success, now everything works with `toggle_hdr = 0` as intended, but I'm hanging at the same place with `toggle_hdr = 1`

Files/Logs:

[moonlight_hdr_launcher_install.log](https://github.com/lyckantropen/moonlight_hdr_launcher/files/5752072/moonlight_hdr_launcher_install.log)

Log file with `toggle_hdr = 1`

[hdr_moonlight_hdr_launcher_log.txt]
(https://github.com/lyckantropen/moonlight_hdr_launcher/files/5752074/hdr_moonlight_hdr_launcher_log.txt)

Log file with `toggle_hdr = 0`

[nohdr_moonlight_hdr_launcher_log.txt](https://github.com/lyckantropen/moonlight_hdr_launcher/files/5752075/nohdr_moonlight_hdr_launcher_log.txt)

`moonlight_hdr_launcher.ini` contents:

```
[options]
# command to launch when the launcher is executed  
; launcher_exe = C:\Program Files (x86)\Steam\steam.exe steam://open/bigpicture

# wait for the launcher process to exit or detach immediately
# useful with gamestream_launchpad to close the connection
# and with toggle_hdr=1
; wait_on_process = 0

# enable HDR on all supported monitors for the duration of the launcher
# only works with wait_on_process=1
; toggle_hdr = 0

## Examples
# launch Steam in Big Picture mode
; launcher_exe = C:\Program Files (x86)\Steam\steam.exe steam://open/bigpicture
; wait_on_process = 0

# launch GOG Galaxy using gamestream_launchpad
; launcher_exe=gamestream_launchpad.exe 2560 1440 gamestream_gog_galaxy.ini
launcher_exe = "C:\Program Files\moonlight_hdr_launcher\gamestream_launchpad.exe" 3840 1600 "C:\Program Files\moonlight_hdr_launcher\gamestream_steam_bp.ini"
wait_on_process=1
toggle_hdr = 1
```

I did not need to modify permissions on the `moonlight_hdr_launcher.ini` file this time 🎊 

I suspect the playnite setting had to do with executing the wrong game in Moonlight (due to having both the steamOS and Mass Effect Andromeda "games" available).

**Comment by lyckantropen** [comment]
Then it turns out there's some crash when using NVAPI that's not being caught and that we're not seeing. I will try making a debug build with core dumps so I can investigate the stack.

Meanwhile there's another solution you might be interested in. I hacked [hdr-toggle](https://github.com/bradgearon/hdr-switch) to make a small executable that toggles HDR. There's a build in my fork [here](https://github.com/lyckantropen/hdr-switch/releases/tag/v0.1-hdr_toggle).

* Put `hdr_toggle.exe` in `C:\Program Files\moonlight_hdr_launcher`.
* Set `toggle_hdr` to `0`.
* In `gamestream_steam_bp.ini` in the `[BACKGROUND]` section uncomment the line adding `hdr_toggle.exe` to the list of executables to run in the background.

If that doesn't work, you can always try installing [hdr-toggle](https://github.com/bradgearon/hdr-switch), use the NON-hdr setup and try turning HDR from the tray using the mouse.

**Comment by lyckantropen** [comment]
If `hdr_toggle.exe` doesn't work either, would you please run it standalone using the command line? It uses the same code but it's a console application as opposed to `MassEffectAndromeda.exe` and may print a useful error message.

**Comment by lyckantropen** [comment]
[Here](https://github.com/lyckantropen/moonlight_hdr_launcher/releases/tag/1.0.6-hdr-toggle-debug) is a debug pre-release that also contains a debug version of `hdr_toggle.exe`. The debug versions should display a window from the Visual C++ runtime when crashed. If you want to be extra helpful, you can [enable debug dumps](https://www.meziantou.net/tip-automatically-create-a-crash-dump-file-on-error.htm).

**Comment by j9ac9k** [comment]
> Then it turns out there's some crash when using NVAPI that's not being caught and that we're not seeing. I will try making a debug build with core dumps so I can investigate the stack.
> 
> Meanwhile there's another solution you might be interested in. I hacked [hdr-toggle](https://github.com/bradgearon/hdr-switch) to make a small executable that toggles HDR. There's a build in my fork [here](https://github.com/lyckantropen/hdr-switch/releases/tag/v0.1-hdr_toggle).
> 
> * Put `hdr_toggle.exe` in `C:\Program Files\moonlight_hdr_launcher`.
> * Set `toggle_hdr` to `0`.
> * In `gamestream_steam_bp.ini` in the `[BACKGROUND]` section uncomment the line adding `hdr_toggle.exe` to the list of executables to run in the background.
> 
> If that doesn't work, you can always try installing [hdr-toggle](https://github.com/bradgearon/hdr-switch), use the NON-hdr setup and try turning HDR from the tray using the mouse.

This ran without error (I did not attempt to try an HDR title like assassin's creed odyssey (which has a nice indicator if HDR is available/running).

In case you're curious, here are the contents of the log

```
2020-12-30 08:36:51: Moonlight HDR Launcher Version 1.0.6
2020-12-30 08:36:51: Working folder read from registry: C:\Program Files\moonlight_hdr_launcher
2020-12-30 08:36:51: argv[0]: MassEffectAndromeda.exe
2020-12-30 08:36:51: Setting current working directory to C:\Program Files\moonlight_hdr_launcher
2020-12-30 08:36:51: Found config file: C:\Program Files\moonlight_hdr_launcher\moonlight_hdr_launcher.ini
2020-12-30 08:36:51: options.launcher_exe="C:\Program Files\moonlight_hdr_launcher\gamestream_launchpad.exe" 3840 1600 "C:\Program Files\moonlight_hdr_launcher\gamestream_steam_bp.ini"
2020-12-30 08:36:51: options.wait_on_process=1
2020-12-30 08:36:51: options.toggle_hdr=0
2020-12-30 08:36:51: Launching '"C:\Program Files\moonlight_hdr_launcher\gamestream_launchpad.exe" 3840 1600 "C:\Program Files\moonlight_hdr_launcher\gamestream_steam_bp.ini"' and waiting for it to complete.
```

I also just installed the pre-release 1.0.7 variant, used `toggle_hdr=1` and appears have have crashed on the same spot; I don't know what the sentry log says, but the local generated log is as follows:

```
2020-12-30 08:51:30: Moonlight HDR Launcher Version 1.0.7
2020-12-30 08:51:30: Working folder read from registry: C:\Program Files\moonlight_hdr_launcher
2020-12-30 08:51:30: argv[0]: MassEffectAndromeda.exe
2020-12-30 08:51:30: Setting current working directory to C:\Program Files\moonlight_hdr_launcher
2020-12-30 08:51:30: Found config file: C:\Program Files\moonlight_hdr_launcher\moonlight_hdr_launcher.ini
2020-12-30 08:51:30: options.launcher_exe="C:\Program Files\moonlight_hdr_launcher\gamestream_launchpad.exe" 3840 1600 "C:\Program Files\moonlight_hdr_launcher\gamestream_steam_bp.ini"
2020-12-30 08:51:30: options.wait_on_process=1
2020-12-30 08:51:30: options.toggle_hdr=1
2020-12-30 08:51:30: Attempting to set HDR mode
```

Also, my apologies, I realized I never thanked you for creating this project and assisting with my issue.  Thanks for your help and for sharing this tool!

**Comment by lyckantropen** [comment]
> This ran without error (I did not attempt to try an HDR title like assassin's creed odyssey (which has a nice indicator if HDR is available/running).

What did you end up doing? Use the hdr-toggle tray or `hdr_toggle.exe`?

> Also, my apologies, I realized I never thanked you for creating this project and assisting with my issue. Thanks for your help and for sharing this tool!

Appreciated! I'm doing it for myself and for street cred ;)

Thanks for testing @j9ac9k , FYI the crash info has been uploaded. It was a crash in my code that I will fix, thanks again.

**Comment by j9ac9k** [comment]
> > This ran without error (I did not attempt to try an HDR title like assassin's creed odyssey (which has a nice indicator if HDR is available/running).
> 
> What did you end up doing? Use the hdr-toggle tray or `hdr_toggle.exe`?

I used `hdr_toggle.exe` in `gamestream_steam_bp.ini`, I'm a sucker for pre-defined config files over manual steps :)

> > Also, my apologies, I realized I never thanked you for creating this project and assisting with my issue. Thanks for your help and for sharing this tool!
> 
> Appreciated! I'm doing it for myself and for street cred ;)

I maintain https://github.com/pyqtgraph/pyqtgraph so I totally get how overwhelming having a project used out in the world can be!

> Thanks for testing @j9ac9k , FYI the crash info has been uploaded. It was a crash in my code that I will fix, thanks again.

Glad to hear you got useful debug information!

**Comment by lyckantropen** [comment]
@j9ac9k All in all, I think the key to running HDR games without an HDR monitor is running Steam Big Picture through the `MassEffectAndromeda.exe` launcher. The HDR toggle will essentially do nothing if there's no HDR monitors.

**Comment by lyckantropen** [comment]
@akenbake Were you able to launch Steam Big Picture using release 1.0.6 or pre-release 1.0.7?

**Comment by j9ac9k** [comment]
> @j9ac9k All in all, I think the key to running HDR games without an HDR monitor is running Steam Big Picture through the `MassEffectAndromeda.exe` launcher. The HDR toggle will essentially do nothing if there's no HDR monitors.

I set `toggle_hdr = 0` in the launcher ini file; enabled the `hdr_toggle.exe` executable in `gamestream_steam_bp.ini` but unfortunately HDR was not recognized when launching Assassin's Creed Odyssey.  Furthermore, launching the game via steam, it did not relay my client monitor aspect ratio (21:9) and attempted to use 16:9 or 16:10 aspect ratio options.

I'm wondering if this can be addressed with some adding launch options to the entry in steam; but that will require further investigation.

Of the Gamestream HDR titles listed here: https://www.nvidia.com/en-us/geforce/forums/gamestream/19/295074/gamestream-hdr-support-list/ I have access to a few other games, which I may also attempt to run.

**Comment by lyckantropen** [comment]
@j9ac9k I only have 2 recommendations on what you could try:

1. Launch BP without gamestream_launchpad:
    
    `moonlight_hdr_launcher.ini`:

    ```ini
    [options]
    launcher_exe = C:\Program Files (x86)\Steam\steam.exe steam://open/bigpicture
    wait_on_process = 0
    toggle_hdr = 0
    ```
    Sadly, we don't know what [tmac666](https://www.nvidia.com/en-us/geforce/forums/user/213217/338010/hdr-fix-for-gamestream-and-steam-big-picture-mode/) is doing exactly. If I get corageous I may try spoofing `steam.exe` and capture the arguments in a sandboxed environment.

2. Tinker with `StreamingSettings.json`. There's a couple of resolution-related settings there:

    ```json
            "DefaultStreamingMode": "3840x2160@60",
            "DefaultConsoleMode": "3840x2160@60",
            "DefaultResolution": "3840x2160",
    ```

Do let me know if you find something out.

**Comment by j9ac9k** [comment]
I tried the second method of changing `StreamingSettings.json`; which did have some nice side-effects of not having my desktop constantly rescale; but resulted in the same place.

I don't think this is a limitation of your tool, I think this is a limitation of steam big picture.  When launching a game from steam big picture, it apparently makes no attempt to pass along the resolution the desktop is currently using, but instead offers the available resolutions of the "attached display".  In other words, I think I'm going to have to get some programmable dummy HDMI dongle and clone my actual monitor and use that instead.  This is just for resolution, maybe HDR could still work w/ a bogus resolution? I don't know...

I'll try with a few other games that supposedly support gamestream HDR.

**Comment by j9ac9k** [comment]
got it working! resolution is bogus (2560x1600)..... I'm using `hdr-toggle.exe` and calling that manually via `gamestream_steam_bp.ini`

The missing piece is that my client is running macOS; I had to edit the moonlight plist file to enable HDR (set `videocfg` value to `3`)...that setting keeps periodically being reset for reasons I don't understand... now to experiment to see if I can have HDR enabled without having to launch steam big-pictures

![Screen Shot 2020-12-30 at 12 16 21 PM](https://user-images.githubusercontent.com/646398/103378997-03416080-4a99-11eb-9e8c-ce2645314e85.png)

**Comment by j9ac9k** [comment]
k, so bad news, ...it's still definitely attached to the virtual display regardless of how I launch it feels like; I may try calling the game manually

good news, launching the game via PlayNite shows HDR as an option I can toggle on/off, so I don't think there exists a dependence on steam big picture...

**Comment by lyckantropen** [comment]
@j9ac9k Are you talking about a hardware HDMI emulator? In terms of software I was thinking if using Microsoft's IddCx (Indirect Display Driver) may be a  solution for game streaming in general (i.e. headless boxes without even an HDMI dongle), but it doesn't support HDR yet.

**Comment by j9ac9k** [comment]
> @j9ac9k Are you talking about a hardware HDMI emulator? In terms of software I was thinking if using Microsoft's IddCx (Indirect Display Driver) may be a solution for game streaming in general (i.e. headless boxes without even an HDMI dongle), but it doesn't support HDR yet.

I think so, I actually don't have any HDMI ports on my GPU, just display ports, so I have [this guy](https://www.amazon.com/FUERAN-DP-DisplayPort-emulator-2560x1600/dp/B071CGCTMY).

To get ultrawide resolutions on the desktop, I had to create a custom resolution through the nvidia control panel:

![image](https://user-images.githubusercontent.com/646398/103419606-a43b2480-4b48-11eb-9d0d-26a3a9aa233e.png)

Unfortunately that custom resolution is not recognized inside games, and I'm just given the non-custom resolution options (this is not an issue with Parsec, not sure how they sorted that out).

I posted on reddit, and got referred to this post: https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU  so I'll give that a go.

Also let me know if you'd like me to migrate this convo to another issue (or elsewhere not in the issue tracker).

**Comment by j9ac9k** [comment]
Sure enough, with the custom resolution utility I was able to get the ultrawide resolution with HDR!

![Screen Shot 2020-12-31 at 1 25 48 PM](https://user-images.githubusercontent.com/646398/103426115-eb86dc80-4b6b-11eb-8935-3c14034be267.png)

Thank you so much for your help with this.  I just want to reinforce that a requirement to make this work on macOS is changing `videocfg` value to 3 (from 0) in `~/Library/Preferences/com.moonlight-stream.Moonlight.plist` (this value has also gone back to 0 on its own on me before, so be sure to check that first if having trouble).

**Comment by j9ac9k** [comment]
I just wanted to add a follow up that from the screenshots it does not appear that HDR is being displayed correctly on macOS (colors are all really really bright).  This is a moonlight issue, devs are aware of the issue but now that HDR can be replicated this should hopefully be easier for them to debug.

**Comment by lyckantropen** [comment]
Thank you so much for your commitment. Would you be inclined to contribute
an osX guide to the readme?

niedz., 3 sty 2021, 17:50 użytkownik Ogi Moore <notifications@github.com>
napisał:

**Comment by j9ac9k** [comment]
I can create a pull request with additions to the README.md file, but I want to emphasize that HDR on macOS will not work with moonlight in its present state even if you setup `moonlight_hdr_launcher` correctly (that said I can add info on how to tell you get getting a HDR picture sent from the gamestream host).

**Comment by lyckantropen** [comment]
Closing due to inactivity from submitter, but it appears the issue has been resolved.
